import { Product } from '@/types/product';

export const products: Product[] = [
    {
        id: 'helmet-wall-stand',
        name: 'Soporte de Pared para Casco + Llaves',
        price: 19000,
        category: 'Hogar',
        images: ['/products/soporte-casco-1.jpg', '/products/soporte-casco-2.jpg'],
        isCustom: false,
        shortDescription: 'Soporte de pared para casco con gancho para llaves.',
        description: 'Soporte de pared resistente para colgar cascos de moto o bicicleta, con gancho inferior integrado para llaves. Ideal para mantener tu espacio organizado y tener todo a la mano. Práctico, resistente y de fácil instalación.',
        colors: ['Negro', 'Blanco', 'Gris'],
        materials: ['PLA', 'PETG'],
        shipping: 'Envíos a todo Colombia · Entregas en Bogotá',
    },
    {
        id: 'soporte-celular-escritorio',
        name: 'Soporte para Celular de Escritorio',
        price: 18000,
        category: 'Oficina',
        images: ['/products/soporte-celular-1.jpg', '/products/soporte-celular-2.jpg', '/products/soporte-celular-3.jpg'],
        isCustom: false,
        shortDescription: 'Soporte estable para celular, ideal para escritorio o mesa de noche. Diseño compacto y práctico.',
        description: 'Soporte para el celular con diseño estable y compacto. Perfecto para videollamadas, ver contenido o mantener el teléfono visible mientras trabajas o estudias.',
        colors: ['Negro', 'Blanco', 'Gris', 'Verde', 'Azul'],
        materials: ['PLA'],
        shipping: 'Envíos a todo Colombia · Entregas en Bogotá',
    },
    {
        id: 'hotwheels-hex-10',
        name: 'Soporte Modular Hot Wheels (10 carros)',
        price: 21000,
        category: 'Coleccionables',
        images: ['/products/hotwheels-stand.jpg', '/products/hotwheels-stand-2.jpg', '/products/hotwheels-stand-3.jpg'],
        isCustom: false,
        shortDescription: 'Exhibidor modular de pared para Hot Wheels (hasta 10 carros).',
        description: 'Soporte modular de pared diseñado para exhibir hasta 10 Hot Wheels de forma ordenada y segura. Su sistema encajable permite unir múltiples módulos entre sí para expandir tu colección y crear una exhibición continua en la pared.',
        colors: ['Negro', 'Blanco'],
        colorImages: {
            'Negro': '/products/hotwheels-stand.jpg',
            'Blanco': '/products/hotwheels-stand-3.jpg',
        },
        materials: ['PLA'],
        shipping: 'Envíos a todo Colombia · Entregas en Bogotá',
        isBestSeller: true,
    },
    {
        id: 'soporte-flotante-control',
        name: 'Soporte Flotante Para Control - Xbox',
        price: 9000,
        category: 'Accesorios',
        images: ['/products/soporte-flotante-1.jpg', '/products/soporte-flotante-2.jpg', '/products/soporte-flotante-3.jpg', '/products/soporte-flotante-4.jpg'],
        isCustom: false,
        shortDescription: 'Mantén tu control organizado, visible y protegido cuando no lo estás usando.',
        description: 'Soporte de escritorio diseñado para sostener tu control de Xbox de forma estable y segura. Ideal para mantener tu espacio ordenado y tu control siempre a la mano. Perfecto para escritorios, mesas de noche o estaciones de juego. Compatible con controles de Xbox Series X | S y Xbox One.',
        colors: ['Negro', 'Blanco', 'Gris', 'Rojo', 'Verde', 'Azul'],
        materials: ['PLA'],
        shipping: 'Envíos a todo Colombia · Entregas en Bogotá',
    },
    {
        id: 'soporte-flotante-control-play',
        name: 'Soporte Flotante Para Control - PlayStation',
        price: 9000,
        category: 'Accesorios',
        images: ['/products/soporte-flotante-1.jpg', '/products/soporte-flotante-2.jpg', '/products/soporte-flotante-3.jpg', '/products/soporte-flotante-4.jpg'],
        isCustom: false,
        shortDescription: 'Mantén tu control organizado, visible y protegido cuando no lo estás usando.',
        description: 'Soporte de escritorio diseñado para sostener tu control de PlayStation de forma estable y segura. Ideal para mantener tu espacio ordenado y tu control siempre a la mano. Perfecto para escritorios, mesas de noche o estaciones de juego. Compatible con controles de PlayStation 5 y PlayStation 4.',
        colors: ['Negro', 'Blanco', 'Gris', 'Rojo', 'Verde', 'Azul'],
        materials: ['PLA'],
        shipping: 'Envíos a todo Colombia · Entregas en Bogotá',
    },
];
